version: '3'
services:
    anchorblock-accounting-mvp-backend:
        build:
            context: .
            dockerfile: ./Dockerfile
        image: anchorblock-accounting-mvp-backend
        ports:
            - '80:3000'
        container_name: anchorblock-accounting-mvp-backend
        volumes:
            - /app/node_modules
